version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: memory-palace-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - memory-palace-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memory-palace-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=memory_palace
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=text-embedding-3-small
      - MAX_FILE_SIZE=52428800
      - UPLOAD_PATH=./uploads
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - memory-palace-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: nginx:alpine
    container_name: memory-palace-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - memory-palace-network

networks:
  memory-palace-network:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local